name: Fuzzing with cifuzz

# Runs all fuzz tests in this repository with cifuzz.

# You need to set CIFUZZ_DOWNLOAD_TOKEN as a repository secret. Get the token
# from https://downloads.code-intelligence.com/.

# Run workflow each time code is pushed to default branch of the repository,
# for every pull request to the default branch and on a schedule. Allow to
# run this workflow manually.
# The scheduled workflow runs every day at 03:50 UTC.
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  schedule:
    - cron: '50 03 * * *'
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest

    permissions:
      # Please comment-out the ones you don't need and uncomment the ones you do need

      # Required to Upload findings to Github code scanning
      security-events: write

      # Required to commit findings to repository
      # contents: write

    steps:
      # Adapt this if you are not running on a container with Debian-based distribution
      - name: Install clang, llvm & lcov
        run: |
          sudo apt update
          sudo apt install cmake clang llvm lcov
          sudo apt install libclang-rt-dev || true # required on on ubuntu 24.04

      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install cifuzz
        uses: "CodeIntelligenceTesting/actions/install-cifuzz@v1"
        with:
          version: 3.12.0
          download-token: ${{ secrets.CIFUZZ_DOWNLOAD_TOKEN }}

      - name: Run fuzzing
        uses: "CodeIntelligenceTesting/actions/run-fuzzing@v1"
        with:
          duration: 15s

      - name: Upload code-scanning report
        uses: "CodeIntelligenceTesting/actions/upload-code-scanning-report@v1"

      # Uncomment this step if you want to commit all findings found when running this workflow:
      # - name: Commit findings and corpus to repository
      #   run: |
      #     git config --global user.name 'Github Action'
      #     git config --global user.email 'zgtm@users.noreply.github.com'
      #     git add .cifuzz-findings
      #     git add .cifuzz-corpus
      #     git commit -m "Automated check-in of cifuzz findings"
      #     git push
